# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "782e5ae53b633a98cdee286490ef6f0d"
name = "MM2 Checkout"
handle = "mm2-checkout"
application_url = "https://jesse-humidity-implementation-obj.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-node-apps.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_draft_orders,customer_read_markets,customer_read_orders,customer_read_store_credit_accounts,customer_write_customers,unauthenticated_read_customer_tags,unauthenticated_write_checkouts,unauthenticated_write_customers,write_cart_transforms,write_customers,write_draft_orders,write_orders"

[auth]
redirect_urls = [
  "https://jesse-humidity-implementation-obj.trycloudflare.com/auth/callback",
  "https://jesse-humidity-implementation-obj.trycloudflare.com/auth/shopify/callback",
  "https://jesse-humidity-implementation-obj.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
