# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d0cf7f8d531385fa4d54a21765b0a1bd"
name = "checkout-app"
handle = "checkout-app-707"
application_url = "https://capture-keyboards-understanding-a.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testtakewithfood.myshopify.com"
include_config_on_deploy = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_draft_orders,customer_read_markets,customer_read_orders,customer_read_store_credit_accounts,customer_write_customers,unauthenticated_read_customer_tags,unauthenticated_write_checkouts,unauthenticated_write_customers,write_cart_transforms,write_customers,write_draft_orders,write_orders"

[auth]
redirect_urls = [
  "https://capture-keyboards-understanding-a.trycloudflare.com/auth/callback",
  "https://capture-keyboards-understanding-a.trycloudflare.com/auth/shopify/callback",
  "https://capture-keyboards-understanding-a.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
